server:
  port: 7085

spring:
  application:
    name: sales-marketing-service

# Eureka configuration
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetch-registry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://192.168.0.20:8761/eureka/
