server:
  port: 7085

spring:
  application:
    name: sales-marketing-service

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

info:
  app:
    name: sales-marketing-service
    description: "TL Express Files Application"
    version: "1.0.0"
