# =============================================================================
# CUSTOMER GATEWAY SERVER - DEVELOPMENT ENVIRONMENT CONFIGURATION
# =============================================================================

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8081  # Same as default

# Eureka configuration for development
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.20:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 10
  instance:
    prefer-ip-address: false  # CHANGED: Use hostname instead of IP
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      zone: ${ZONE:default}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,gateway"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: "customer-gateway-server"
    description: "TL Express Customer API Gateway - Development"
    version: "1.0.0"
    environment: "development"
