# =============================================================================
# AUTHORIZATION SERVICE CONFIGURATION - DEV DEFAULT
# =============================================================================

server:
  port: 7081

spring:
  application:
    name: authorization-service

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.20:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 10
  instance:
    prefer-ip-address: false  # CHANGED: Use hostname instead of IP
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      zone: ${ZONE:default}
