# =============================================================================
# USER SERVICE CONFIGURATION - DEV DEFAULT
# =============================================================================

server:
  port: 7082

spring:
  application:
    name: user-service
# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.20:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 10
  instance:
    prefer-ip-address: true  # Use IP address for service discovery
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      zone: ${ZONE:default}
