# =============================================================================
# GATEWAY SERVER - PRODUCTION ENVIRONMENT CONFIGURATION
# =============================================================================

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # Production-specific gateway routes can be added here

server:
  port: 8080  # Production port

# Eureka configuration for production
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.20:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 10
  instance:
    prefer-ip-address: false  # CHANGED: Use hostname instead of IP
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      zone: ${ZONE:default}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
        exclude: "env,configprops,beans,mappings,shutdown,threaddump,heapdump"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    show-details: never
    show-components: never
  endpoint:
    shutdown:
      enabled: false
    health:
      probes:
        enabled: true

info:
  app:
    name: "gateway-server"
    description: "TL Express API Gateway - Production"
    version: "1.0.0"
    environment: "production"
