server:
  port: 7084

# =============================================================================
# LOCATION SERVICE CONFIGURATION - PRODUCTION ENVIRONMENT
# =============================================================================

spring:
  application:
    name: location-service

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.20:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 10
  instance:
    prefer-ip-address: false  # CHANGED: Use hostname instead of IP
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      zone: ${ZONE:default}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: "location-service"
    description: "TL Express Location Service - PROD"
    version: "1.0.0"
