server:
  port: 7084

# =============================================================================
# LOCATION SERVICE CONFIGURATION - PRODUCTION ENVIRONMENT
# =============================================================================

spring:
  application:
    name: location-service

# Eureka configuration
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetch-registry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: "location-service"
    description: "TL Express Location Service - PROD"
    version: "1.0.0"